development:
  adapter: postgresql
  database: demo001_development
  host: localhost

test:
  adapter: postgresql
  database: demo001_test
  host: localhost

production:
  adapter: postgresql
  database: demo001_production
  host: localhost